version: '2'

services:
  nginx:
    image: nginx-alpine
    ports: [8080:80]
    expose: 80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgresql
    environment:
      POSTGRES_PASSWORD: 'password'
  app:
    build: .
    links:
      - postgresql
    depends_on:
      - postgresql
      - nginx
    ports:
      - 3000:3000
    command: ["/bin/bash", "-c", "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s -e production -b 0.0.0.0 -p 3000"]
